[package]
name = "ghakuf"
version = "0.1.0"
authors = ["acknak <acknak39@gmail.com>"]

[dependencies]
byteorder = "1.0.0"
log = "0.3"

[dev-dependencies]
env_logger = "0.3"

[lib]
name = "ghakuf"
path = "src/lib.rs"
